### ISSUE TITLE
iteritems is no longer supported in python 3

### ISSUE THREAD

**Issue by vazir** [orokusaki/pycard#1]
Hi! Please fix a simple issue - as in subj - it does not run in 3.4 and probably any 3x as:

> the dict.iterkeys(), dict.iteritems() and dict.itervalues() methods are no longer supported.

line 93 to:
for brand, regexp in self.BRANDS.items():

thanks and regards,
Anton

**Comment by orokusaki** [comment]
@vazir thanks for the report - I've just fixed this in v0.9.5
