### ISSUE TITLE
Why this package isn't on PyPI?

### ISSUE THREAD

**Issue by rougeth** [orokusaki/pycard#5]

**Comment by emyller** [comment]
Bump! This tiny library is amazing, it definitely should be at PyPI.

However, there's already a lib "PyCard" in there, which is about creating vCard objects. Although we do like the name, the author (@orokusaki) may consider changing the name of this library to avoid conflicts and confusing.

@rougeth Do you have a suggestion?

**Comment by rougeth** [comment]
Nice to hear that @emyller. My suggestions are (best ones first):
- pyccard
- ccard
- creditcard
- pycreditcard

**Comment by orokusaki** [comment]
Hey @rougeth @emyller - thanks for the suggestions / help. I'm going to come back and take a look at all 3 open issues this weekend. I've been slammed lately.

**Comment by orokusaki** [comment]
@emyller @rougeth what do you two think about `captain-pycard`?

**Comment by rougeth** [comment]
@orokusaki that's awesome! 😆

**Comment by emyller** [comment]
![Captain Picard facepalm](http://i.imgur.com/uFKjUy5.png)

@orokusaki ...Yeah. Not bad at all! :wink:

**Comment by paulmcgoldrick** [comment]
Make it so!

**Comment by emyller** [comment]
Hey @orokusaki. Did you have a chance to upload it?
PS: Enjoy the end of the year.

**Comment by orokusaki** [comment]
@emyller I haven't yet - I'm sorry. I actually got stuck trying to determine everything required to do so. It seems like you need a dev and production PyPi account, etc. Do you have any experience with PyPi uploads yourself?

**Comment by orokusaki** [comment]
Also, have a happy New Years too, @emyller!

**Comment by rougeth** [comment]
@orokusaki There's no need of dev account (actually it's a test account that can be used to test the upload without really creating a package, see https://test.pypi.org).

I recommend twine to upload to PyPI.Take a look: https://github.com/pypa/twine.

Happy New Year guys! :)

**Comment by emyller** [comment]
Hey @orokusaki! Once you have your PyPI [regular] account, you just `python setup.py register` and `python setup.py sdist upload` to have it online. There are a few other things you can do but that's the simplest route. :wink:

Or, as @rougeth recommended, use twine to take advantage of a secure (HTTPS) connection to transmit data to PyPI in older Python versions and other perks.

Happy New Years everybody!

**Comment by orokusaki** [comment]
Thanks, you two are great!

I'll get this uploaded tonight after work.

**Comment by orokusaki** [comment]
@emyller @rougeth @paulmcgoldrick 

[captain-pycard is official](https://pypi.python.org/pypi/captain-pycard)!

All these years, I've avoided uploading things to PyPi... and it was this easy! Thanks for the help.

**Comment by emyller** [comment]
That's great news, @orokusaki! Thanks for this.

**Comment by rougeth** [comment]
Awesome!! 👏 👏 👏
