### ISSUE TITLE
Add support for new MasterCard BINs (2-series)

### ISSUE THREAD

**Issue by emyller** [orokusaki/pycard#6]
MasterCard has just introduced their new Bank Identification Number series, which will start with the number `2`. According to their [explanation page](https://www.mastercard.us/en-us/issuers/get-support/2-series-bin-expansion.html):

> Mastercard® has received an additional range of 2-series numbers to add to the 5-series that we currently provide. The 2-series BINs operate in the same way as the 5-series and we have made changes to our systems to accommodate the new numbers. Readiness for the 2-series across our issuers, merchants and other partners is tracking on target dates listed below. Mastercard customer financial institutions can expect to be issued 2-series BINs starting in 2017.

**Comment by emyller** [comment]
According to [Wikipedia](https://en.wikipedia.org/wiki/Payment_card_number), the 2-series range is comprehended by 222100–272099.

**Comment by orokusaki** [comment]
Thanks @emyller! I've merged your patch.
